---
all:
  vars:
    node_network: testnet
    timezone: Europe/Amsterdam
  hosts:
    operator:
      ansible_host: localhost
      ansible_connection: local
    core:
      ansible_host: csp-core-node
      ansible_user: ada
      node_host: csp-core-node
      node_port: 6000
    monitor:
      ansible_host: csp-relay-node-01
      ansible_user: ada
  children:
    relays:
      hosts:
        relay-01:
          ansible_host: csp-relay-node-01
          node_host: 111.222.333.444
      vars:
        ansible_user: ada
        node_port: 6000