---
- hosts: operator
  tasks:
  - include_role:
      name: cardano-node
  - include_role:
      name: cardano-address
  - include_role:
      name: cardano-node-service
  - include_role:
      name: cardano-cli-magic-args
  - include_role:
      name: cardano-hd-wallet
  - include_role:
      name: cardano-stake-pool