---
- include_role:
    name: file-exists-guard
  vars:
    item: /usr/local/bin/cardano-address
- name: Install cardano-hd-address
  become: yes
  ansible.builtin.copy:
    src: files/cardano-hd-address
    dest: "/usr/local/bin"
    mode: '0755'