---
- include_role:
    name: file-exists-guard
  vars:
    item: /usr/local/bin/cardano-cli
- name: Install cardano-stake-pool
  become: yes
  ansible.builtin.copy:
    src: files/cardano-stake-pool
    dest: "/usr/local/bin"
    mode: '0755'